### ISSUE TITLE
 Лабораторная работа № 2 Вопросы

### ISSUE THREAD

**Issue by readysloth** [sekibura/Arh_VS_Labs#2]
+ В каком сегменте исполняемого файла располагаются статические и глобальные перменные?
+ Что такое выравнивание данных и зачем оно нужно?

**Comment by sekibura** [comment]
> * В каком сегменте исполняемого файла располагаются статические и глобальные перменные?

Статические и глобальные переменные располагаются в сегменте данных (data segment)

> * Что такое выравнивание данных и зачем оно нужно?

Выравнивание данных - разновидность оптимизации работы с данными на уровне процессора. Обусловлено это тем, что компьютер быстрее работает с данными, представленными в памяти, в особом виде. 
Пример:

1)
```
[байт 0] [байт 1] [байт 2] [байт 3] [байт 4] [байт 5] [байт 6] [байт 7]...
[        машинное слово 0         ] [        машинное слово 1         ]...
```
2)
```
[байт 0] [байт 1] [байт 2] [байт 3] [байт 4] [байт 5] [байт 6] [байт 7] [байт 8]...
         [          машинное слово         ] [     ещё одно машинное слово     ]...
```
В данном случае, на большинстве компьютеров, комбинированные в четвёрки машинные слова - первым образом читаются быстро, а вот машинные слова второго типа (то есть, те, которые не получаются шагами по 4 от нуля) — медленно.

Так же, в случае, если данные имеют _длину_< длины слова, оставшееся место слова не используется:
```
[    ] [    ] [    ] [    ] [    ] [    ] [    ] [    ] [    ] [    ] [    ] [    ]
[  x ] { потерянные байты } [             y           ] [  z ] { потерянные байты }
```

Это не единственный пример оптимизации путем выравнивания слова, оптимизация для разных архитектур может отличаться.
