### ISSUE TITLE
Лабораторная работа № 3 Вопросы

### ISSUE THREAD

**Issue by readysloth** [sekibura/Arh_VS_Labs#3]
+ Чем опасно переполнение стека?
+ Зачем нужны ассемблерные модули, если пишем на высокоуровневых языках? (1-2)
+  Через какие этапы проходит исходный код, чтобы превратиться в исполняемый файл?
   - На каком из них будут использованы ассемблерные модули?

**Comment by sekibura** [comment]
###  _Чем опасно переполнение стека?_

Переполнение стека опасно тем, что является уязвимостью, которая может быть использована злоумышленниками.  Происходить это может из-за того, что в каком-либо месте программы происходит копирование данных из одного участка памяти в другой без проверки того, достаточно ли для них места там, куда их копируют.  Если данных слишком много, то часть их попадает за границы предназначенного места- происходит "переполнение стека". Умелое использование того, куда попадают "лишние данные" может позволить злоумышленнику выполнить любой код на компьютере, где произошло переполнение.
###  _Зачем нужны ассемблерные модули, если пишем на высокоуровневых языках? (1-2)_

Ассемблерные модули (вставки) могут применяться может преследовать разные цели:

- **Оптимизация**:
  Порой, вручную написанный код, может быть производительнее кода, сгенерированного компилятором

- **Доступ к специфичным инструкциям процессора**

- **Системные вызовы**
  Языки программирования высокого уровня редко предоставляют прямую возможность делать системные вызовы, для этих целей используется ассемблерный код

###  _Через какие этапы проходит исходный код, чтобы превратиться в исполняемый файл?_
Исходный код проходит этапы:

- Препроцессинг

- Компиляция

- Ассемблирование

- Компоновка

### _На каком из них будут использованы ассемблерные модули?_
На этапе компиляции происходит компиляция кода без директив(получен на прошлом этапе) в ассемблерный код. То есть, используя ассемблерный модуль (вставку), мы вручную создаем ассемблерный код для конкретного участка без участия компилятора. Далее, на этапе ассемблирования, весь код преобразуется в объектный файл.

**Comment by sekibura** [comment]
> * Чем опасно переполнение стека?

Переполнение стека опасно тем, что является уязвимостью, которая может быть использована злоумышленниками.  Происходить это может из-за того, что в каком-либо месте программы происходит копирование данных из одного участка памяти в другой без проверки того, достаточно ли для них места там, куда их копируют.  Если данных слишком много, то часть их попадает за границы предназначенного места- происходит "переполнение стека". Умелое использование того, куда попадают "лишние данные" может позволить злоумышленнику выполнить любой код на компьютере, где произошло переполнение.

> * Зачем нужны ассемблерные модули, если пишем на высокоуровневых языках? (1-2)

Ассемблерные модули (вставки) могут применяться может преследовать разные цели:

- **Оптимизация**: 
  Порой, вручную написанный код, может быть производительнее кода, сгенерированного компилятором

- **Доступ к специфичным инструкциям процессора**

- **Системные вызовы**
  Языки программирования высокого уровня редко предоставляют прямую возможность делать системные вызовы, для этих целей используется ассемблерный код

> * Через какие этапы проходит исходный код, чтобы превратиться в исполняемый файл?
Исходный код проходит этапы:

- Препроцессинг

- Компиляция

- Ассемблирование

- Компоновка
>   * На каком из них будут использованы ассемблерные модули?






На этапе компиляции происходит компиляция кода без директив(получен на прошлом этапе) в ассемблерный код. То есть, используя ассемблерный модуль (вставку), мы вручную создаем ассемблерный код для конкретного участка без участия компилятора. Далее, на этапе ассемблирования, весь код преобразуется в объектный файл.
